# Generated by Django 4.2.3 on 2023-07-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='tags',
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.ManyToManyField(to='forecast.tag'),
        ),
    ]
