# Generated by Django 4.2.3 on 2023-07-06 02:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('forecast', '0003_remove_newspost_tags_tag_news_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
